"""
Test fixtures for OilTrace backend tests.

Uses PostgreSQL via testcontainers (production-like) instead of SQLite
to ensure RLS policies, UUID generation, and JSONB operators work correctly.

If testcontainers is not available, falls back to SQLite for basic unit tests.

Install: pip install testcontainers[postgresql] psycopg2-binary
"""

import os
import pytest
import pytest_asyncio
from typing import AsyncGenerator, Generator
from httpx import AsyncClient, ASGITransport
from sqlalchemy import create_engine, text
from sqlalchemy.orm import sessionmaker, Session

# ── Conditional PostgreSQL / SQLite ─────────────────────────────────

USE_REAL_PG = os.environ.get("OILTRACE_TEST_DB", "").lower() in ("postgres", "pg")

if USE_REAL_PG:
    try:
        from testcontainers.postgres import PostgresContainer

        @pytest.fixture(scope="session")
        def postgres_container():
            """Spin up a real PostgreSQL container for testing."""
            with PostgresContainer("postgres:16-alpine") as pg:
                yield pg

        @pytest.fixture
        def db_url(postgres_container) -> str:
            return postgres_container.get_connection_url()

    except ImportError:
        USE_REAL_PG = False
        print("WARNING: testcontainers not installed. Falling back to SQLite. "
              "RLS tests will be SKIPPED. Install with: "
              "pip install testcontainers[postgresql] psycopg2-binary")


if not USE_REAL_PG:
    # Fallback to SQLite for basic unit tests
    TEST_DATABASE_URL = "sqlite:///./test.db"

    @pytest.fixture
    def db_url() -> str:
        return TEST_DATABASE_URL


# ── Application Imports (after env setup) ──────────────────────────

# These imports must happen after the database decision
# In a real project, you'd structure this so app modules can be imported
# before the database is connected.

@pytest.fixture
def db_session(db_url: str) -> Generator[Session, None, None]:
    """Create a fresh database session for each test."""
    from app.database import Base, get_engine

    engine = create_engine(db_url)
    Base.metadata.create_all(bind=engine)
    TestSession = sessionmaker(bind=engine)
    session = TestSession()

    yield session

    session.close()
    Base.metadata.drop_all(bind=engine)


@pytest_asyncio.fixture
async def client(db_session: Session) -> AsyncGenerator[AsyncClient, None]:
    """HTTP test client with overridden database dependency."""
    from app.main import app
    from app.database import get_db

    async def override_get_db():
        yield db_session

    app.dependency_overrides[get_db] = override_get_db

    transport = ASGITransport(app=app)
    async with AsyncClient(transport=transport, base_url="http://test/api/v1") as ac:
        yield ac

    app.dependency_overrides.clear()


# ── Auth Helpers ────────────────────────────────────────────────────

@pytest.fixture
def consumer_jwt() -> str:
    """Return a mock consumer JWT for testing.

    In production, these are generated by Supabase Auth.
    For tests, we patch the verify_jwt dependency to return fake claims.
    """
    return "mock-consumer-jwt-token"


@pytest.fixture
def driver_jwt() -> str:
    return "mock-driver-jwt-token"


@pytest.fixture
def owner_jwt() -> str:
    return "mock-owner-jwt-token"


@pytest.fixture
def mock_rls_session(db_session: Session):
    """Seed minimal data for RLS boundary tests.

    Creates two consumers and one driver so we can verify isolation.
    """
    from app.models import Profile, Consumer, Driver, Owner
    from uuid import uuid4

    # These IDs simulate auth.uid() values from Supabase Auth
    consumer_a_id = uuid4()
    consumer_b_id = uuid4()
    driver_id = uuid4()
    owner_id = uuid4()

    profiles = [
        Profile(id=consumer_a_id, role="consumer", full_name="Consumer A"),
        Profile(id=consumer_b_id, role="consumer", full_name="Consumer B"),
        Profile(id=driver_id, role="driver", full_name="Driver One"),
        Profile(id=owner_id, role="owner", full_name="Owner Admin"),
    ]
    for p in profiles:
        db_session.add(p)

    consumers = [
        Consumer(profile_id=consumer_a_id, business_name="Karinderya A"),
        Consumer(profile_id=consumer_b_id, business_name="Karinderya B"),
    ]
    for c in consumers:
        db_session.add(c)

    db_session.add(Driver(profile_id=driver_id, status="available"))
    db_session.add(Owner(profile_id=owner_id, company_name="OilTrace Corp"))

    db_session.commit()

    return {
        "consumer_a_id": consumer_a_id,
        "consumer_b_id": consumer_b_id,
        "driver_id": driver_id,
        "owner_id": owner_id,
    }
