/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(consumer)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(consumer)'}/history` | `/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(consumer)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(consumer)'}/rewards` | `/rewards`; params?: Router.UnknownInputParams; } | { pathname: `${'/(consumer)'}/history/[id]` | `/history/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(consumer)'}/dashboard` | `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(consumer)'}/history` | `/history`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(consumer)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(consumer)'}/rewards` | `/rewards`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(consumer)'}/history/[id]` | `/history/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(consumer)'}/dashboard${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `${'/(consumer)'}/history${`?${string}` | `#${string}` | ''}` | `/history${`?${string}` | `#${string}` | ''}` | `${'/(consumer)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(consumer)'}/rewards${`?${string}` | `#${string}` | ''}` | `/rewards${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(consumer)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(consumer)'}/history` | `/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(consumer)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(consumer)'}/rewards` | `/rewards`; params?: Router.UnknownInputParams; } | `${'/(consumer)'}/history/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/history/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `${'/(consumer)'}/history/[id]` | `/history/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
